### ISSUE TITLE
No joy on samples/modules view for me!

### ISSUE THREAD

**Issue by DruggedBunny** [Hezkore/deprecated-vscode-blitzmax-support#11]
Hi Hezkore, per the [worklog](https://www.syntaxbomb.com/index.php/topic,5824.60.html), I'm still getting nothing in the samples/modules dropdowns. The dropdowns 'turn' when clicked, but nothing... drops down!

BlitzMaxNG is sitting at `D:\DevTools\Blitz\BlitzMaxNG\bin` and this is set in my PATH, so the folders are at:

```
D:\DevTools\Blitz\BlitzMaxNG\samples
D:\DevTools\Blitz\BlitzMaxNG\mod
```

I'm on latest 1.29.0 extension update, just installed/restarted. Latest blitzmax.org NG release too.

EDIT: Relevant? Using Windows 7, 64-bit.

Quick hack from the worklog post follows...

> Hmm, still no joy! On looking up where the log file is, I found the VSC developer tools thing, which does show this:
> 
> [code]
> EntryNotFound (FileSystemError): 
> 	at massageError (c:\Users\James\.vscode\extensions\hezkore.blitzmax-1.26.1\out\samplesTree.js:35:43)
> 	at handleResult (c:\Users\James\.vscode\extensions\hezkore.blitzmax-1.26.1\out\samplesTree.js:27:20)
> 	at c:\Users\James\.vscode\extensions\hezkore.blitzmax-1.26.1\out\samplesTree.js:66:51
> 	at FSReqCallback.oncomplete (fs.js:153:23)
> [/code]
> 
> I see the sample scanning code in [code]c:\Users\James\.vscode\extensions\hezkore.blitzmax-1.26.1\out\samplesTree.js[/code], but can't really follow it!
> 
> The error seems to be pointing to [code]handleResult(resolve, reject, error, normalizeNFC(children)))[/code] in [code]function readdir(path)[/code]. At least, that seems to be what sits at samplesTree.js:66:51.
> 
> No idea if that's any use!
>

**Comment by Hezkore** [comment]
`PATH` is never used.
The only thing that matters is what folder you've pointed the extension to.
(_File > Preferences > Settings > Extensions > BlitzMax > Bmx Path_)
But I don't think that's the issue anyway.
I'm thinking the process may be taking too long and is straight up just rejected.
But I've tried the samples tree on multiple computers and even on a slow virtual machine and I can't reproduce this issue, so I'm not sure that's the case.
Oh, and the code you managed to find in the logs was removed in update 1.26.2, so it's no longer relevant.

But its all a moot point as the 'Samples' tree will be replaced by a newly written 'Help' tree.
It'll take a while for me to get this new update out as I'm working on replacing the documentation system as well.
But hopefully it'll solve your problem.

I'll ask if the problem still exists after I've pushed the new update.

**Comment by DruggedBunny** [comment]
OK, thanks for looking.

I just ran SysInternals Process Monitor on it, on the offchance, and one interesting thing I found was that while it does reference my path, `D:\DevTools\Blitz\BlitzMaxNG\mod`, there are references also to `C:\DevTools\Blitz\BlitzMaxNG\mod` and `C:\DevTools\Blitz\BlitzMaxNG\samples` -- I don't have a C:\DevTools, so it's like it's replacing D: with C: somewhere, for some reason.

I notice that when it (sometimes) outputs the BlitzMax path in the console, it starts with lower-case d:\DevTools... wonder if that's relevant somehow.

Not sure why it would be right in one place but not another.

![wrongdrive](https://user-images.githubusercontent.com/1781537/79637697-6f816b80-8179-11ea-95a3-c56647c9b1cd.jpg)

**Comment by Hezkore** [comment]
I've pushed version 1.30.0 to the marketplace.
Could you give that version a go and report back?

**Comment by DruggedBunny** [comment]
Hmm, modules works! Samples just does what it did before, ie. the little arrow points down, but there's still nothing there. The samples folder is present in my setup, and full of samples...

**Comment by Hezkore** [comment]
Very strange! I'm beginning to suspect it might be some sort of permission issue.
I have BlitzMax in a similar path: **`D:\Applications\Dev\BlitzMaxNG\`** and it works without any issues.
It also works on my Linux and MacOS machines with similar paths.
Nothing is written in **PATH**.
Could you make sure that VSCode has read access to the **`Samples`** folder, and that it actually contains something heh.

**Comment by DruggedBunny** [comment]
Dunno, I've compared the permissions dialogs side-by-side and they appear to be the same for all users.

Done various faffing about to try and understand what's going on, to not much avail, but when it comes down to it, running SysInternals Process Monitor on it and selecting the Samples dropdown shows it's still actually looking for `C:\DevTools\Blitz\BlitzMaxNG\samples` rather than `D:\DevTools\Blitz\BlitzMaxNG\samples` -- no idea why, it's like it's defaulting to the C: drive even though I don't have such a path and never have! Even re-checked my %PATH% and there's definitely just the D:\ folder.
